### ISSUE TITLE
Motor controllers set to random values on reboot

### ISSUE THREAD

**Issue by zeroDecoder** [DanG100/yunServerSoftware#2]
The linux OS throws some garbage on the serial line at start up (most likely debug data) that the arduino interprets as joystick values. This makes the robots drive around uncontrollably after a reboot or brownout until the YUN reconnects to the FMS access point. This is very unsafe!

**Comment by zeroDecoder** [comment]
Added fix https://github.com/Saint-Francis-Robotics-Team2367/yunServerSoftware/commit/f818f02cf6c73b5769cf3fb478a684a01441b02a.
Still needs to be tested.

**Comment by DanG100** [comment]
it is mostly fixed
